# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-11 23:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('scale', models.PositiveIntegerField(blank=True, default=0, help_text='The magnitude of a thing, in whole numbers.  0 is average/medium/normal/default/human-sized.  e.g.: -2=XS, -1=S, 0=M, 1=L, 2=XL, 3=2XL and so on.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('subkeywords', models.ManyToManyField(blank=True, help_text='Allows a structured category hierarchy for classification browsing.', related_name='_keyword_subkeywords_+', to='arcfire.Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('position', models.CharField(choices=[('absolute', 'Absolute'), ('relative', 'Relative')], default='relative', help_text='"Absolute" positions establish a new reference point for sublocations: they are always relative to the ABSOLUTE_LOCATION in settings.  "Relative" positions are relative to their nearest "Absolute" parent, otherwise they are also relative to ABSOLUTE_LOCATION.  See: wiki/position', max_length=10)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='In decimal.', max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='In meters.', max_digits=9, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=3, help_text='In meters.', max_digits=9, null=True)),
                ('sublocations', models.ManyToManyField(blank=True, help_text='The main location indicates the reference point (e.g. the center); if sublocations are relative, they are  to this point.', related_name='_location_sublocations_+', to='arcfire.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('aspect', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('front', 'Front'), ('back', 'Back'), ('left', 'Left Side'), ('right', 'Right Side'), ('top', 'Top'), ('bottom', 'Bottom'), ('internal', 'Internal'), ('external', 'External')], default='primary', max_length=10, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(help_text='In pixels.', null=True)),
                ('height', models.PositiveIntegerField(help_text='In pixels.', null=True)),
                ('image', models.ImageField(height_field=models.PositiveIntegerField(help_text='In pixels.', null=True), null=True, upload_to='', width_field=models.PositiveIntegerField(help_text='In pixels.', null=True))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('scale', models.PositiveIntegerField(blank=True, default=0, help_text='The magnitude of a thing, in whole numbers.  0 is average/medium/normal/default/human-sized.  e.g.: -2=XS, -1=S, 0=M, 1=L, 2=XL, 3=2XL and so on.', null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='arcfire.Keyword')),
                ('locations', models.ManyToManyField(blank=True, to='arcfire.Location')),
                ('pictures', models.ManyToManyField(blank=True, to='arcfire.Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('aspect', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('front', 'Front'), ('back', 'Back'), ('left', 'Left Side'), ('right', 'Right Side'), ('top', 'Top'), ('bottom', 'Bottom'), ('internal', 'Internal'), ('external', 'External')], default='primary', max_length=10, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('predicate', models.CharField(choices=[('related', 'is related to'), ('attract', 'is attracted to'), ('cause', 'is caused by'), ('child', 'is child of'), ('control', 'is controlled by'), ('friend', 'is friend of'), ('inside', 'is inside of'), ('mate', 'is mate of'), ('own', 'is owned by'), ('part', 'is part of'), ('result', 'is result of'), ('subject', 'is subject of'), ('type', 'is type of')], default='related', max_length=10)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='arcfire.Relation')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='arcfire.Relation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('scale', models.PositiveIntegerField(blank=True, default=0, help_text='The magnitude of a thing, in whole numbers.  0 is average/medium/normal/default/human-sized.  e.g.: -2=XS, -1=S, 0=M, 1=L, 2=XL, 3=2XL and so on.', null=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=3, help_text='In kilograms.', max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, help_text='In meters.', max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, help_text='In meters.', max_digits=12, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, help_text='In meters.', max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Thing')),
            ],
            options={
                'abstract': False,
            },
            bases=('arcfire.thing', models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Thing')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('none', 'None'), ('other', 'Other')], max_length=10)),
                ('ki', models.DecimalField(decimal_places=3, default=0.5, help_text='Choose a number between 0.0 and 1.0.  The default is 0.5, which represents the life-force of Joe the Plumber.  0.0 is empty space, somewhere past Pluto.  1.0 is God himself. See wiki/ki for more information.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('name_secondary', models.CharField(blank=True, max_length=255, verbose_name='Given Name')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
            bases=('arcfire.thing', models.Model),
        ),
        migrations.AddField(
            model_name='thing',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='arcfire.Keyword'),
        ),
        migrations.AddField(
            model_name='thing',
            name='locations',
            field=models.ManyToManyField(blank=True, to='arcfire.Location'),
        ),
        migrations.AddField(
            model_name='thing',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='arcfire.Picture'),
        ),
        migrations.AddField(
            model_name='thing',
            name='plans',
            field=models.ManyToManyField(blank=True, to='arcfire.Plan'),
        ),
        migrations.AddField(
            model_name='thing',
            name='properties',
            field=models.ManyToManyField(blank=True, to='arcfire.Property'),
        ),
        migrations.AddField(
            model_name='thing',
            name='relations',
            field=models.ManyToManyField(through='arcfire.Relation', to='arcfire.Thing'),
        ),
        migrations.AddField(
            model_name='place',
            name='plans',
            field=models.ManyToManyField(blank=True, to='arcfire.Plan'),
        ),
        migrations.AddField(
            model_name='place',
            name='properties',
            field=models.ManyToManyField(blank=True, to='arcfire.Property'),
        ),
        migrations.AddField(
            model_name='place',
            name='relations',
            field=models.ManyToManyField(through='arcfire.Relation', to='arcfire.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='arcfire.Keyword'),
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='arcfire.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='arcfire.Picture'),
        ),
        migrations.AddField(
            model_name='event',
            name='plans',
            field=models.ManyToManyField(blank=True, to='arcfire.Plan'),
        ),
        migrations.AddField(
            model_name='event',
            name='properties',
            field=models.ManyToManyField(blank=True, to='arcfire.Property'),
        ),
        migrations.AddField(
            model_name='event',
            name='relations',
            field=models.ManyToManyField(through='arcfire.Relation', to='arcfire.Event'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('arcfire.person', models.Model),
        ),
    ]
