# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-29 22:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('front', 'Front'), ('back', 'Back'), ('left', 'Left Side'), ('right', 'Right Side'), ('top', 'Top'), ('bottom', 'Bottom'), ('internal', 'Internal'), ('external', 'External')], default='primary', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scale', models.PositiveIntegerField(default=0)),
                ('ki', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('keywords', models.ManyToManyField(related_name='_event_keywords_+', to='arcfire.Event')),
                ('properties', models.ManyToManyField(related_name='_event_properties_+', to='arcfire.Event')),
                ('purposes', models.ManyToManyField(related_name='_event_purposes_+', to='arcfire.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scale', models.PositiveIntegerField(default=0)),
                ('ki', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mass', models.DecimalField(decimal_places=3, help_text='In kilograms.', max_digits=12)),
                ('height', models.DecimalField(decimal_places=3, help_text='In meters.', max_digits=12)),
                ('width', models.DecimalField(decimal_places=3, help_text='In meters.', max_digits=12)),
                ('length', models.DecimalField(decimal_places=3, help_text='In meters.', max_digits=12)),
                ('heading', models.DecimalField(decimal_places=3, help_text='In radians.  The angle between the direction the item is pointing and true North.', max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scale', models.PositiveIntegerField(default=0)),
                ('ki', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('time', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=6, help_text='In decimal.', max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='In meters.', max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=3, help_text='In meters.', max_digits=9)),
                ('kind', models.CharField(choices=[('begin', 'Begin'), ('change', 'Change'), ('end', 'End')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scale', models.PositiveIntegerField(default=0)),
                ('ki', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('keywords', models.ManyToManyField(related_name='_memory_keywords_+', to='arcfire.Memory')),
                ('properties', models.ManyToManyField(related_name='_memory_properties_+', to='arcfire.Memory')),
                ('purposes', models.ManyToManyField(related_name='_memory_purposes_+', to='arcfire.Memory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scale', models.PositiveIntegerField(default=0)),
                ('ki', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('width', models.PositiveIntegerField(help_text='In pixels.')),
                ('height', models.PositiveIntegerField(help_text='In pixels.')),
                ('image', models.ImageField(height_field=models.PositiveIntegerField(help_text='In pixels.'), upload_to='', width_field=models.PositiveIntegerField(help_text='In pixels.'))),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='arcfire.Aspect')),
                ('keywords', models.ManyToManyField(related_name='_picture_keywords_+', to='arcfire.Picture')),
                ('properties', models.ManyToManyField(related_name='_picture_properties_+', to='arcfire.Picture')),
                ('purposes', models.ManyToManyField(related_name='_picture_purposes_+', to='arcfire.Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scale', models.PositiveIntegerField(default=0)),
                ('ki', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('file', models.FileField(upload_to='')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='arcfire.Aspect')),
                ('keywords', models.ManyToManyField(related_name='_plan_keywords_+', to='arcfire.Plan')),
                ('properties', models.ManyToManyField(related_name='_plan_properties_+', to='arcfire.Plan')),
                ('purposes', models.ManyToManyField(related_name='_plan_purposes_+', to='arcfire.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('related', 'is related to'), ('attract', 'is attracted to'), ('cause', 'is caused by'), ('child', 'is child of'), ('control', 'is controlled by'), ('friend', 'is friend of'), ('inside', 'is inside of'), ('mate', 'is mate of'), ('own', 'is owned by'), ('part', 'is part of'), ('result', 'is result of'), ('subject', 'is subject of'), ('type', 'is type of')], default='related', max_length=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='arcfire.RelationJoin')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='arcfire.RelationJoin')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Item')),
            ],
            options={
                'abstract': False,
            },
            bases=('arcfire.item', models.Model),
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Item')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('none', 'None'), ('other', 'Other')], default=None, max_length=10, null=True)),
                ('species', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('arcfire.item',),
        ),
        migrations.AddField(
            model_name='plan',
            name='relations',
            field=models.ManyToManyField(through='arcfire.RelationJoin', to='arcfire.Plan'),
        ),
        migrations.AddField(
            model_name='picture',
            name='relations',
            field=models.ManyToManyField(through='arcfire.RelationJoin', to='arcfire.Picture'),
        ),
        migrations.AddField(
            model_name='memory',
            name='relations',
            field=models.ManyToManyField(through='arcfire.RelationJoin', to='arcfire.Memory'),
        ),
        migrations.AddField(
            model_name='location',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcfire.Item'),
        ),
        migrations.AddField(
            model_name='location',
            name='keywords',
            field=models.ManyToManyField(related_name='_location_keywords_+', to='arcfire.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='properties',
            field=models.ManyToManyField(related_name='_location_properties_+', to='arcfire.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='purposes',
            field=models.ManyToManyField(related_name='_location_purposes_+', to='arcfire.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='relations',
            field=models.ManyToManyField(through='arcfire.RelationJoin', to='arcfire.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.ManyToManyField(related_name='_item_keywords_+', to='arcfire.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='pictures',
            field=models.ManyToManyField(to='arcfire.Picture'),
        ),
        migrations.AddField(
            model_name='item',
            name='plans',
            field=models.ManyToManyField(to='arcfire.Plan'),
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.ManyToManyField(related_name='_item_properties_+', to='arcfire.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='purposes',
            field=models.ManyToManyField(related_name='_item_purposes_+', to='arcfire.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='relations',
            field=models.ManyToManyField(through='arcfire.RelationJoin', to='arcfire.Item'),
        ),
        migrations.AddField(
            model_name='event',
            name='relations',
            field=models.ManyToManyField(through='arcfire.RelationJoin', to='arcfire.Event'),
        ),
        migrations.AddField(
            model_name='memory',
            name='life',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='arcfire.Life'),
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='collections', to='arcfire.Item'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('arcfire.life',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('life_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Life')),
                ('members', models.ManyToManyField(related_name='organizations', to='arcfire.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('arcfire.person', models.Model),
        ),
    ]
