# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-12 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places_primary', to='arcfire.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('none', 'None'), ('other', 'Other')], max_length=10),
        ),
    ]
