# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-29 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='arcfire.Person'),
        ),
    ]
