# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0002_auto_20151030_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='arcfire.Picture'),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties',
            field=models.ManyToManyField(blank=True, to='arcfire.Property'),
        ),
    ]
