# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-12 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0003_auto_20151112_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(7000, 1, 1, 0, 0), help_text='Time begins anew in the year 7000.'),
        ),
    ]
