# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-30 21:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0004_auto_20151030_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationjoin',
            old_name='type',
            new_name='predicate',
        ),
        migrations.AddField(
            model_name='location',
            name='position',
            field=models.CharField(choices=[('absolute', 'Absolute'), ('relative', 'Relative')], default='relative', help_text='"Absolute" positions establish a new reference point for sublocations: they are always relative to the ABSOLUTE_LOCATION in settings.  "Relative" positions are relative to their nearest "Absolute" parent, otherwise they are also relative to ABSOLUTE_LOCATION.  See: wiki/position', max_length=10),
        ),
        migrations.AddField(
            model_name='location',
            name='sublocations',
            field=models.ManyToManyField(blank=True, help_text='The main location indicates the reference point (e.g. the center); if sublocations are relative, they are  to this point.', related_name='_location_sublocations_+', to='arcfire.Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='arcfire.Keyword'),
        ),
        migrations.AlterField(
            model_name='item',
            name='locations',
            field=models.ManyToManyField(blank=True, to='arcfire.Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='arcfire.Picture'),
        ),
        migrations.AlterField(
            model_name='item',
            name='plans',
            field=models.ManyToManyField(blank=True, to='arcfire.Plan'),
        ),
        migrations.AlterField(
            model_name='item',
            name='properties',
            field=models.ManyToManyField(blank=True, to='arcfire.Property'),
        ),
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(blank=True, choices=[('begin', 'Begin'), ('change', 'Change'), ('end', 'End')], max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ki',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Choose a number between 0.0 and 1.0.  The default is 0.5, which represents the life-force of Joe the Plumber.  0.0 is empty space, somewhere past Pluto.  1.0 is God himself. See wiki/ki for more information.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.PositiveIntegerField(help_text='In pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(height_field=models.PositiveIntegerField(help_text='In pixels.', null=True), null=True, upload_to='', width_field=models.PositiveIntegerField(help_text='In pixels.', null=True)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.PositiveIntegerField(help_text='In pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='ki',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Choose a number between 0.0 and 1.0.  The default is 0.5, which represents the life-force of Joe the Plumber.  0.0 is empty space, somewhere past Pluto.  1.0 is God himself. See wiki/ki for more information.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='relationjoin',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='arcfire.RelationJoin'),
        ),
        migrations.AlterField(
            model_name='relationjoin',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='arcfire.RelationJoin'),
        ),
    ]
