# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0005_auto_20151030_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='species',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='species',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.AddField(
            model_name='keyword',
            name='subkeywords',
            field=models.ManyToManyField(blank=True, help_text='Allows a structured category hierarchy for classification browsing.', related_name='_keyword_subkeywords_+', to='arcfire.Keyword'),
        ),
    ]
