# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-22 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0005_auto_20151112_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2015, 11, 22, 13, 16, 23, 811498), help_text='Time begins anew in the year 7000.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='predicate',
            field=models.CharField(choices=[('related', 'is related to'), ('attract', 'is attracted to'), ('cause', 'is caused by'), ('child', 'is child of'), ('heir', 'is heir of'), ('control', 'is controlled by'), ('friend', 'is friend of'), ('inside', 'is inside of'), ('mate', 'is mate of'), ('own', 'is owned by'), ('part', 'is part of'), ('result', 'is result of'), ('subject', 'is subject of'), ('type', 'is type of')], default='related', max_length=10),
        ),
    ]
