# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-27 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0006_auto_20151122_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 19, 690007)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 24, 227836)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 29, 403903)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time begins anew in the year 7000.'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 34, 859425)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 39, 444496)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 43, 694395)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 49, 562198)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 7, 55, 210906)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 27, 21, 8, 6, 586700)),
            preserve_default=False,
        ),
    ]
