# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0007_auto_20151127_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
