# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcfire', '0008_auto_20151207_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arcfire.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('arcfire.person', models.Model),
        ),
    ]
